name: jfp
favicon: null
layout_spectrum: 0.50192
typography_spectrum: 0.17096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f7f5'
    - '#02070a'
    - '#c7b4ae'
    - '#fb2d28'
    - '#46555b'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
