layout_spectrum: 0.700966130476445
typography_spectrum: 0.4284290657378733
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.6238445700146258
  lightness: 0.9590467098169029
  saturation: 0.7603755951859057
  rhythmicContrast: 0.5675819194875658
name: jfp
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
