name: jfp
favicon: null
layout_spectrum: 0.50192
typography_spectrum: 0.46820204914547503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7468226170167327
  lightness: 0.12956754304468632
  saturation: 0.21514091920107603
  rhythmicContrast: 0.8956733006052673
purpose: []
